import '../styles/globals.css';
import { MascotaTheme } from '../lib/theming';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return <>
    <Head>
      <title> Mascota de Cafe </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/css2?family=Lobster&family=Montserrat:wght@400;500&family=Open+Sans&family=Poppins&display=swap" rel="stylesheet"></link>
    </Head>

    <ThemeProvider theme={MascotaTheme}>
      <CssBaseline />
      <Component {...pageProps} />
    </ThemeProvider>
  </>;
}

export default MyApp;
